### ISSUE TITLE
error

### ISSUE THREAD

**Issue by lianfeng30** [nanshihui/normal_hark_lite#1]
E:\normal_hark_lite>python __init__.py 10.0.1.210 elasticsearch
root    : INFO     Load Plugin: component.struts.struts2032.P
root    : INFO     Module keywords: struts -> (['struts'], 'component')
root    : INFO     Module rules: struts -> (['struts'], 'component')
root    : INFO     Load Plugin: component.elasticsearch.elasticsearch_nodestate.
P
root    : INFO     Module keywords: elasticsearch -> (['elasticsearch'], 'compon
ent')
root    : INFO     Module rules: elasticsearch -> (['elasticsearch'], 'component
')
root    : INFO     Load Plugin: component.elasticsearch.elasticsearch_groovy.P
root    : INFO     Module keywords: elasticsearch -> (['elasticsearch'], 'compon
ent')
root    : INFO     Module rules: elasticsearch -> (['elasticsearch'], 'component
')
Traceback (most recent call last):
  File "__init__.py", line 9, in <module>
    a=default.PocController(logger=logger)
  File "E:\normal_hark_lite\plugins\default.py", line 26, in __init__
    self.loader()
  File "E:\normal_hark_lite\plugins\default.py", line 92, in loader
    self.__load_component_plugins(map(lambda module_info: module_info['module_na
me'], self.modules_list))
  File "E:\normal_hark_lite\plugins\default.py", line 88, in __load_component_pl
ugins
    self.__load_component_detail_plugins(module_name)
  File "E:\normal_hark_lite\plugins\default.py", line 75, in __load_component_de
tail_plugins
    modules_list = self.__get_component_detail_list(componentname)
  File "E:\normal_hark_lite\plugins\default.py", line 42, in __get_component_det
ail_list
    modules_list = set(map(lambda item: isdir(join(path, item)) and item, listdi
r(path)))
WindowsError: [Error 3] : 'E:\\normal_hark_lite\\plugins\\middileware/*.*'

..

**Comment by nanshihui** [comment]
建议在linux下   因为路径 Windows和linux  不一样
